-- FlexTrip Final PostgreSQL Schema
-- This script creates all tables and relationships for the application.
-- This version is focused on ground transport and does not include the future flights module.

-- Drop existing tables in reverse order of creation to avoid foreign key conflicts
DROP TABLE IF EXISTS "BookedLeg" CASCADE;
DROP TABLE IF EXISTS "TransportationBooking" CASCADE;
DROP TABLE IF EXISTS "AdHocTransportBooking" CASCADE;
DROP TABLE IF EXISTS "AccommodationBooking" CASCADE;
DROP TABLE IF EXISTS "ActivityBooking" CASCADE;
DROP TABLE IF EXISTS "DayUseBooking" CASCADE;
DROP TABLE IF EXISTS "VisaBooking" CASCADE;
DROP TABLE IF EXISTS "Payment" CASCADE;
DROP TABLE IF EXISTS "PaymentMethod" CASCADE;
DROP TABLE IF EXISTS "BookingParticipant" CASCADE;
DROP TABLE IF EXISTS "Booking" CASCADE;
DROP TABLE IF EXISTS "Company" CASCADE;
DROP TABLE IF EXISTS "Client" CASCADE;
DROP TABLE IF EXISTS "Customer" CASCADE;
DROP TABLE IF EXISTS "RoomDailyInventory" CASCADE;
DROP TABLE IF EXISTS "RoomInventory" CASCADE;
DROP TABLE IF EXISTS "RoomCategory" CASCADE;
DROP TABLE IF EXISTS "RoomType" CASCADE;
DROP TABLE IF EXISTS "RoomView" CASCADE;
DROP TABLE IF EXISTS "MealPlan" CASCADE;
DROP TABLE IF EXISTS "TripVehicleAssignment" CASCADE;
DROP TABLE IF EXISTS "TripLeg" CASCADE;
DROP TABLE IF EXISTS "TripVehicleRequirement" CASCADE;
DROP TABLE IF EXISTS "Trip" CASCADE;
DROP TABLE IF EXISTS "Vehicle" CASCADE;
DROP TABLE IF EXISTS "TransportationCategory" CASCADE;
DROP TABLE IF EXISTS "Driver" CASCADE;
DROP TABLE IF EXISTS "Compensation" CASCADE;
DROP TABLE IF EXISTS "Employee" CASCADE;
DROP TABLE IF EXISTS "Role" CASCADE;
DROP TABLE IF EXISTS "Team" CASCADE;
DROP TABLE IF EXISTS "Supplier" CASCADE;
DROP TABLE IF EXISTS "Hotel" CASCADE;
DROP TABLE IF EXISTS "Airport" CASCADE; -- Will be dropped if it exists
DROP TABLE IF EXISTS "City" CASCADE;
DROP TABLE IF EXISTS "Country" CASCADE;
DROP TABLE IF EXISTS "ActivityType" CASCADE;


-- Create Tables

CREATE TABLE "Customer" (
  "CustomerID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CustomerType" VARCHAR NOT NULL
);

CREATE TABLE "Client" (
  "ClientID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CustomerID" INT UNIQUE NOT NULL,
  "FullName" VARCHAR NOT NULL,
  "PhoneNumber1" VARCHAR,
  "PhoneNumber2" VARCHAR,
  "Email" VARCHAR UNIQUE,
  "NationalID" VARCHAR UNIQUE,
  "CityOfResidenceID" INT,
  "Age" INT,
  "NationalityCountryID" INT
);

CREATE TABLE "Company" (
  "CompanyID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CustomerID" INT UNIQUE NOT NULL,
  "SupplierID" INT UNIQUE NOT NULL,
  "ContactName" VARCHAR NOT NULL,
  "ContactPhone" VARCHAR NOT NULL
);

CREATE TABLE "Employee" (
  "EmployeeID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FirstName" VARCHAR NOT NULL,
  "LastName" VARCHAR NOT NULL,
  "username" VARCHAR UNIQUE NOT NULL,
  "password" VARCHAR NOT NULL,
  "PhoneNumber" VARCHAR UNIQUE,
  "NationalID" VARCHAR UNIQUE,
  "JoinedDate" DATE,
  "RoleID" INT NOT NULL,
  "TeamID" INT NOT NULL
);

CREATE TABLE "Role" (
  "RoleID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RoleName" VARCHAR UNIQUE NOT NULL,
  "RoleDescription" TEXT
);

CREATE TABLE "Team" (
  "TeamID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TeamName" VARCHAR UNIQUE NOT NULL,
  "TeamDescription" TEXT
);

CREATE TABLE "Supplier" (
  "SupplierID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" VARCHAR UNIQUE NOT NULL,
  "ContactInfo" TEXT
);

CREATE TABLE "Driver" (
  "DriverID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FirstName" VARCHAR NOT NULL,
  "LastName" VARCHAR NOT NULL,
  "LicenseNumber" VARCHAR UNIQUE,
  "PhoneNumber" VARCHAR
);

CREATE TABLE "Compensation" (
  "CompensationID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "EmployeeID" INT UNIQUE NOT NULL,
  "BasicSalary" DECIMAL NOT NULL,
  "CommissionRate" DECIMAL
);

CREATE TABLE "Country" (
  "CountryID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CountryName" VARCHAR UNIQUE NOT NULL
);

CREATE TABLE "City" (
  "CityID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CityName" VARCHAR NOT NULL,
  "CountryID" INT NOT NULL
);

CREATE TABLE "Hotel" (
  "HotelID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" VARCHAR NOT NULL,
  "Description" TEXT,
  "Address" TEXT,
  "CityID" INT NOT NULL,
  "StarRating" DECIMAL,
  "DirectHotelContactInfo" TEXT
);

CREATE TABLE "RoomCategory" (
  "RoomCategoryID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CategoryName" VARCHAR UNIQUE NOT NULL,
  "CategoryDescription" TEXT
);

CREATE TABLE "RoomType" (
  "RoomTypeID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TypeName" VARCHAR UNIQUE NOT NULL,
  "TypeDescription" TEXT
);

CREATE TABLE "RoomView" (
  "RoomViewID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ViewName" VARCHAR UNIQUE NOT NULL,
  "ViewDescription" TEXT
);

CREATE TABLE "MealPlan" (
  "MealPlanID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PlanName" VARCHAR UNIQUE NOT NULL
);

CREATE TABLE "RoomInventory" (
  "InventoryID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "HotelID" INT NOT NULL,
  "SupplierID" INT NOT NULL,
  "RoomCategoryID" INT NOT NULL,
  "RoomTypeID" INT NOT NULL,
  "RoomViewID" INT NOT NULL,
  "Quantity" INT NOT NULL,
  "ValidFromDate" DATE NOT NULL,
  "ValidToDate" DATE NOT NULL
);

CREATE TABLE "RoomDailyInventory" (
  "RoomDailyInventoryID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "InventoryID" INT NOT NULL,
  "InventoryDate" DATE NOT NULL,
  "AvailableQuantity" INT NOT NULL
);

CREATE TABLE "TransportationCategory" (
  "TransportationCategoryID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "VehicleType" VARCHAR NOT NULL,
  "SeatCapacity" INT NOT NULL
);

CREATE TABLE "Vehicle" (
  "VehicleID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TransportationCategoryID" INT NOT NULL,
  "SupplierID" INT NOT NULL,
  "LicensePlate" VARCHAR UNIQUE,
  "VehicleIdentifier" VARCHAR
);

CREATE TABLE "Trip" (
  "TripID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TripName" VARCHAR,
  "TripDate" DATE NOT NULL,
  "TripType" VARCHAR,
  "PairedTripID" INT
);

CREATE TABLE "TripVehicleRequirement" (
  "TripVehicleRequirementID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TripID" INT NOT NULL,
  "TransportationCategoryID" INT NOT NULL,
  "Quantity" INT NOT NULL
);

CREATE TABLE "TripLeg" (
  "TripLegID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TripID" INT NOT NULL,
  "LegOrder" INT NOT NULL,
  "OriginCityID" INT NOT NULL,
  "DestinationCityID" INT NOT NULL,
  "DepartureDateTime" TIMESTAMP NOT NULL,
  "ArrivalDateTime" TIMESTAMP NOT NULL,
  "AvailableSeats" INT NOT NULL
);

CREATE TABLE "TripVehicleAssignment" (
  "TripVehicleAssignmentID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TripID" INT NOT NULL,
  "VehicleID" INT,
  "DriverID" INT,
  "GuideEmployeeID" INT
);

CREATE TABLE "ActivityType" (
  "ActivityTypeID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ActivityTypeName" VARCHAR UNIQUE NOT NULL,
  "Description" TEXT
);

CREATE TABLE "Booking" (
  "BookingID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CustomerID" INT NOT NULL,
  "EmployeeID" INT NOT NULL,
  "BookingCreationDate" TIMESTAMP NOT NULL DEFAULT (now()),
  "LastModifiedDate" TIMESTAMP NOT NULL DEFAULT (now()),
  "LastModifiedByEmployeeID" INT NOT NULL,
  "BookingStatus" VARCHAR NOT NULL,
  "GrandTotal" DECIMAL,
  "CollectionAmount" DECIMAL
);

CREATE TABLE "VisaBooking" (
  "VisaBookingID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BookingID" INT NOT NULL,
  "DestinationCountryID" INT NOT NULL,
  "VisaType" VARCHAR,
  "NumberOfPeople" INT NOT NULL,
  "Comments" TEXT,
  "Status" VARCHAR NOT NULL
);

CREATE TABLE "DayUseBooking" (
  "DayUseBookingID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BookingID" INT NOT NULL,
  "HotelID" INT NOT NULL,
  "CheckInDate" DATE NOT NULL,
  "NumberOfAdults" INT NOT NULL,
  "NumberOfChildren" INT NOT NULL,
  "Comments" TEXT
);

CREATE TABLE "PaymentMethod" (
  "PaymentMethodID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MethodName" VARCHAR UNIQUE NOT NULL
);

CREATE TABLE "Payment" (
  "PaymentID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BookingID" INT NOT NULL,
  "PaymentDate" TIMESTAMP NOT NULL,
  "Amount" DECIMAL NOT NULL,
  "PaymentMethodID" INT NOT NULL,
  "Currency" VARCHAR(3) NOT NULL,
  "AttachmentURL" VARCHAR
);

CREATE TABLE "BookingParticipant" (
  "BookingParticipantID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BookingID" INT NOT NULL,
  "FirstName" VARCHAR NOT NULL,
  "LastName" VARCHAR NOT NULL,
  "NationalID" VARCHAR,
  "CityOfResidenceID" INT,
  "Age" INT
);

CREATE TABLE "AccommodationBooking" (
  "AccommodationBookingID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BookingID" INT NOT NULL,
  "InventoryID" INT,
  "SupplierID" INT,
  "CheckInDate" DATE NOT NULL,
  "CheckOutDate" DATE NOT NULL,
  "NumberOfRoomsBooked" INT NOT NULL,
  "NumberOfAdults" INT NOT NULL,
  "NumberOfChildren" INT NOT NULL,
  "MealPlanID" INT NOT NULL,
  "Status" VARCHAR NOT NULL,
  "LeadParticipantNationalityCountryID" INT
);

CREATE TABLE "TransportationBooking" (
  "TransportationBookingID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BookingID" INT NOT NULL,
  "NumberOfSeatsBooked" INT NOT NULL,
  "Comments" TEXT
);

CREATE TABLE "BookedLeg" (
  "BookedLegID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TransportationBookingID" INT NOT NULL,
  "TripLegID" INT NOT NULL
);

CREATE TABLE "AdHocTransportBooking" (
  "AdHocTransportBookingID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BookingID" INT NOT NULL,
  "SupplierID" INT,
  "TransportationCategoryID" INT NOT NULL,
  "NumberOfSeats" INT NOT NULL,
  "OriginCityID" INT NOT NULL,
  "DestinationCityID" INT NOT NULL,
  "TravelDateTime" TIMESTAMP NOT NULL,
  "Status" VARCHAR NOT NULL
);

CREATE TABLE "ActivityBooking" (
  "ActivityBookingID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BookingID" INT NOT NULL,
  "ActivityTypeID" INT NOT NULL,
  "SupplierID" INT,
  "ActivityDate" DATE NOT NULL,
  "PlaceOfActivityCityID" INT NOT NULL,
  "NumberOfAdults" INT NOT NULL,
  "NumberOfChildren" INT NOT NULL,
  "Comments" TEXT,
  "Status" VARCHAR NOT NULL
);

-- Create Indexes and Foreign Keys

CREATE UNIQUE INDEX ON "City" ("CityName", "CountryID");
CREATE UNIQUE INDEX ON "RoomDailyInventory" ("InventoryID", "InventoryDate");

ALTER TABLE "Client" ADD FOREIGN KEY ("CustomerID") REFERENCES "Customer" ("CustomerID");
ALTER TABLE "Client" ADD FOREIGN KEY ("CityOfResidenceID") REFERENCES "City" ("CityID");
ALTER TABLE "Client" ADD FOREIGN KEY ("NationalityCountryID") REFERENCES "Country" ("CountryID");

ALTER TABLE "Company" ADD FOREIGN KEY ("CustomerID") REFERENCES "Customer" ("CustomerID");
ALTER TABLE "Company" ADD FOREIGN KEY ("SupplierID") REFERENCES "Supplier" ("SupplierID");

ALTER TABLE "Employee" ADD FOREIGN KEY ("RoleID") REFERENCES "Role" ("RoleID");
ALTER TABLE "Employee" ADD FOREIGN KEY ("TeamID") REFERENCES "Team" ("TeamID");

ALTER TABLE "Compensation" ADD FOREIGN KEY ("EmployeeID") REFERENCES "Employee" ("EmployeeID");

ALTER TABLE "Hotel" ADD FOREIGN KEY ("CityID") REFERENCES "City" ("CityID");

ALTER TABLE "City" ADD FOREIGN KEY ("CountryID") REFERENCES "Country" ("CountryID");

ALTER TABLE "RoomInventory" ADD FOREIGN KEY ("HotelID") REFERENCES "Hotel" ("HotelID");
ALTER TABLE "RoomInventory" ADD FOREIGN KEY ("SupplierID") REFERENCES "Supplier" ("SupplierID");
ALTER TABLE "RoomInventory" ADD FOREIGN KEY ("RoomCategoryID") REFERENCES "RoomCategory" ("RoomCategoryID");
ALTER TABLE "RoomInventory" ADD FOREIGN KEY ("RoomTypeID") REFERENCES "RoomType" ("RoomTypeID");
ALTER TABLE "RoomInventory" ADD FOREIGN KEY ("RoomViewID") REFERENCES "RoomView" ("RoomViewID");

ALTER TABLE "RoomDailyInventory" ADD FOREIGN KEY ("InventoryID") REFERENCES "RoomInventory" ("InventoryID");

ALTER TABLE "Vehicle" ADD FOREIGN KEY ("TransportationCategoryID") REFERENCES "TransportationCategory" ("TransportationCategoryID");
ALTER TABLE "Vehicle" ADD FOREIGN KEY ("SupplierID") REFERENCES "Supplier" ("SupplierID");

ALTER TABLE "Trip" ADD FOREIGN KEY ("PairedTripID") REFERENCES "Trip" ("TripID");

ALTER TABLE "TripVehicleRequirement" ADD FOREIGN KEY ("TripID") REFERENCES "Trip" ("TripID");
ALTER TABLE "TripVehicleRequirement" ADD FOREIGN KEY ("TransportationCategoryID") REFERENCES "TransportationCategory" ("TransportationCategoryID");

ALTER TABLE "TripLeg" ADD FOREIGN KEY ("TripID") REFERENCES "Trip" ("TripID");
ALTER TABLE "TripLeg" ADD FOREIGN KEY ("OriginCityID") REFERENCES "City" ("CityID");
ALTER TABLE "TripLeg" ADD FOREIGN KEY ("DestinationCityID") REFERENCES "City" ("CityID");

ALTER TABLE "TripVehicleAssignment" ADD FOREIGN KEY ("TripID") REFERENCES "Trip" ("TripID");
ALTER TABLE "TripVehicleAssignment" ADD FOREIGN KEY ("VehicleID") REFERENCES "Vehicle" ("VehicleID");
ALTER TABLE "TripVehicleAssignment" ADD FOREIGN KEY ("DriverID") REFERENCES "Driver" ("DriverID");
ALTER TABLE "TripVehicleAssignment" ADD FOREIGN KEY ("GuideEmployeeID") REFERENCES "Employee" ("EmployeeID");

ALTER TABLE "VisaBooking" ADD FOREIGN KEY ("BookingID") REFERENCES "Booking" ("BookingID");
ALTER TABLE "VisaBooking" ADD FOREIGN KEY ("DestinationCountryID") REFERENCES "Country" ("CountryID");

ALTER TABLE "DayUseBooking" ADD FOREIGN KEY ("BookingID") REFERENCES "Booking" ("BookingID");
ALTER TABLE "DayUseBooking" ADD FOREIGN KEY ("HotelID") REFERENCES "Hotel" ("HotelID");

ALTER TABLE "Booking" ADD FOREIGN KEY ("CustomerID") REFERENCES "Customer" ("CustomerID");
ALTER TABLE "Booking" ADD FOREIGN KEY ("EmployeeID") REFERENCES "Employee" ("EmployeeID");
ALTER TABLE "Booking" ADD FOREIGN KEY ("LastModifiedByEmployeeID") REFERENCES "Employee" ("EmployeeID");

ALTER TABLE "Payment" ADD FOREIGN KEY ("BookingID") REFERENCES "Booking" ("BookingID");
ALTER TABLE "Payment" ADD FOREIGN KEY ("PaymentMethodID") REFERENCES "PaymentMethod" ("PaymentMethodID");

ALTER TABLE "BookingParticipant" ADD FOREIGN KEY ("BookingID") REFERENCES "Booking" ("BookingID");
ALTER TABLE "BookingParticipant" ADD FOREIGN KEY ("CityOfResidenceID") REFERENCES "City" ("CityID");

ALTER TABLE "AccommodationBooking" ADD FOREIGN KEY ("BookingID") REFERENCES "Booking" ("BookingID");
ALTER TABLE "AccommodationBooking" ADD FOREIGN KEY ("InventoryID") REFERENCES "RoomInventory" ("InventoryID");
ALTER TABLE "AccommodationBooking" ADD FOREIGN KEY ("SupplierID") REFERENCES "Supplier" ("SupplierID");
ALTER TABLE "AccommodationBooking" ADD FOREIGN KEY ("MealPlanID") REFERENCES "MealPlan" ("MealPlanID");
ALTER TABLE "AccommodationBooking" ADD FOREIGN KEY ("LeadParticipantNationalityCountryID") REFERENCES "Country" ("CountryID");

ALTER TABLE "TransportationBooking" ADD FOREIGN KEY ("BookingID") REFERENCES "Booking" ("BookingID");

ALTER TABLE "BookedLeg" ADD FOREIGN KEY ("TransportationBookingID") REFERENCES "TransportationBooking" ("TransportationBookingID");
ALTER TABLE "BookedLeg" ADD FOREIGN KEY ("TripLegID") REFERENCES "TripLeg" ("TripLegID");

ALTER TABLE "AdHocTransportBooking" ADD FOREIGN KEY ("BookingID") REFERENCES "Booking" ("BookingID");
ALTER TABLE "AdHocTransportBooking" ADD FOREIGN KEY ("SupplierID") REFERENCES "Supplier" ("SupplierID");
ALTER TABLE "AdHocTransportBooking" ADD FOREIGN KEY ("TransportationCategoryID") REFERENCES "TransportationCategory" ("TransportationCategoryID");
ALTER TABLE "AdHocTransportBooking" ADD FOREIGN KEY ("OriginCityID") REFERENCES "City" ("CityID");
ALTER TABLE "AdHocTransportBooking" ADD FOREIGN KEY ("DestinationCityID") REFERENCES "City" ("CityID");

ALTER TABLE "ActivityBooking" ADD FOREIGN KEY ("BookingID") REFERENCES "Booking" ("BookingID");
ALTER TABLE "ActivityBooking" ADD FOREIGN KEY ("ActivityTypeID") REFERENCES "ActivityType" ("ActivityTypeID");
ALTER TABLE "ActivityBooking" ADD FOREIGN KEY ("SupplierID") REFERENCES "Supplier" ("SupplierID");
ALTER TABLE "ActivityBooking" ADD FOREIGN KEY ("PlaceOfActivityCityID") REFERENCES "City" ("CityID");
